### ISSUE TITLE
cleanup_push causes crash for debug build with clang

### ISSUE THREAD

**Issue by binarycraft007** [tidwall/neco#20]
I found a crash only happens with debug build when using the library, found the reason is the implicit array as handler in neco.h
```c
#define neco_cleanup_push(routine, arg) {__neco_c0(&(char[32]){0},routine,arg);
#define neco_cleanup_pop(execute)        __neco_c1(execute);}
```
Suggest this change to fix the crash:

```diff
❯ git diff neco.h                              
diff --git a/neco.h b/neco.h
index 6b905c5..f9155c5 100644
--- a/neco.h
+++ b/neco.h
@@ -225,7 +225,7 @@ int neco_cancel_dl(int64_t id, int64_t deadline);
 int neco_setcanceltype(int type, int *oldtype);
 int neco_setcancelstate(int state, int *oldstate);
 
-#define neco_cleanup_push(routine, arg) {__neco_c0(&(char[32]){0},routine,arg);
+#define neco_cleanup_push(routine, arg) {char _handler[32] = {0}; __neco_c0(&_handler,routine,arg);
 #define neco_cleanup_pop(execute)        __neco_c1(execute);}
 
 /// @}
```

```gdb
Program received signal SIGILL, Illegal instruction.
0x0000000001014acc in cleanup_push (handler=0x7ffff60c7a08, routine=0x10412b0 <cleanup_free_host>, arg=0x1056580) at /home/binarycraft/projects/neco/src/neco.c:7683
warning: Source file is more recent than executable.
7683        handler->routine = routine;
(gdb) bt
#0  0x0000000001014acc in cleanup_push (handler=0x7ffff60c7a08, routine=0x10412b0 <cleanup_free_host>, arg=0x1056580) at /home/binarycraft/projects/neco/src/neco.c:7683
#1  0x0000000001014a75 in __neco_c0 (cl=0x7ffff60c7a08, routine=0x10412b0 <cleanup_free_host>, arg=0x1056580) at /home/binarycraft/projects/neco/src/neco.c:7701
#2  0x0000000001040b17 in getaddrinfo_from_tcp_addr_dl (addr=0x1001c4c "localhost:19203", tcp_vers=0, res=0x7ffff60c7b00, deadline=9223372036854775807) at /home/binarycraft/projects/neco/src/neco.c:6792
#3  0x0000000001041357 in listen_tcp_dl (addr=0x1001c4c "localhost:19203", tcp_vers=0, deadline=9223372036854775807) at /home/binarycraft/projects/neco/src/neco.c:6973
#4  0x00000000010121c4 in serve_dl (network=0x1001f1c "tcp", address=0x1001c4c "localhost:19203", deadline=9223372036854775807) at /home/binarycraft/projects/neco/src/neco.c:7029
#5  0x0000000001012045 in neco_serve_dl (network=0x1001f1c "tcp", address=0x1001c4c "localhost:19203", deadline=9223372036854775807) at /home/binarycraft/projects/neco/src/neco.c:7043
#6  0x0000000001012327 in neco_serve (network=0x1001f1c "tcp", address=0x1001c4c "localhost:19203") at /home/binarycraft/projects/neco/src/neco.c:7072
#7  0x00000000010086e2 in __neco_main (argc=1, argv=0x7fffffffdd68) at /home/binarycraft/projects/neco/examples/echo-server.c:21
#8  0x00000000010086af in _neco_main (argc=2, argv=0x1056430) at /home/binarycraft/projects/neco/examples/echo-server.c:20
#9  0x000000000102f172 in coentry (udata=0x10563e0) at /home/binarycraft/projects/neco/src/neco.c:3827
#10 0x0000000001033437 in sco_entry (udata=0x10563e0) at /home/binarycraft/projects/neco/src/neco.c:2019
#11 0x0000000001028b19 in llco_entry_wrap (arg=0x0) at /home/binarycraft/projects/neco/src/neco.c:1189
#12 0x0000000001028895 in llco_entry (arg=0x0) at /home/binarycraft/projects/neco/src/neco.c:1195
#13 0xdeaddeaddeaddead in ?? ()
#14 0x0000000000000000 in ?? ()
```

**Comment by tidwall** [comment]
I would like to reproduce.  Could you provide more information about your system?
I suspect it's an alignment issue and ideally it could be fixed without introducing new thread globals.

**Comment by binarycraft007** [comment]
> I would like to reproduce. Could you provide more information about your system? I suspect it's an alignment issue and ideally it could be fixed without introducing new thread globals.

Sure, I am using zig build system, the system is x86_64 archlinux, here is the command to build and reproduce the crash:
```shell
zig build-exe -lc -I./ -DLLCO_NOUNWIND neco.c examples/echo-server.c
❯ ./neco

=== Crash on main thread ===

------ STACK TRACE ------

Illegal instruction
```

**Comment by binarycraft007** [comment]
> ideally it could be fixed without introducing new thread globals.

The above change is not thread global though, just explicitly defined the handler.

**Comment by tidwall** [comment]
Thanks! I was able to reproduce. Your suggestion worked and I just pushed the fix.

**Comment by binarycraft007** [comment]
> Thanks! I was able to reproduce. Your suggestion worked and I just pushed the fix.

Come to think of it, maybe the expression &(char[32]){0} confused the compiler and it didn't initialize the array correctly, with the explicitly defined array, we can be sure it's initialized.

**Comment by tidwall** [comment]
Yeah. I'm not exactly sure what happened. 
The zig cc compiler is something I don't have a lot of experience with personally but it's nice to know that it now works.
